INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET /static/css/reset.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:40] "[37mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/css/ihome/index.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/js/ihome/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.eot HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/images/home01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/images/home03.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:14:41] "[37mGET /static/images/home02.jpg HTTP/1.1[0m" 200 -
ERROR app.py:1891 Exception on /api/v1/image_codes/123 [GET]
Traceback (most recent call last):
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\env\my_flask\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\api_1_0\verify_code.py", line 27, in get_image_code
    name, text, image_data = captcha.generate_captcha()
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\utils\captcha\captcha.py", line 219, in generate_captcha
    self.initialize()
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\utils\captcha\captcha.py", line 71, in initialize
    self._text = text if text else random.sample(string.uppercase + string.uppercase + '3456789', 4)
AttributeError: module 'string' has no attribute 'uppercase'
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:15:41] "[35m[1mGET /api/v1/image_codes/123 HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:15:41] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/v1/image_codes/123 [GET]
Traceback (most recent call last):
  File "E:\env\my_flask\lib\site-packages\PIL\ImageFile.py", line 496, in _save
    fh = fp.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\env\my_flask\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\env\my_flask\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\api_1_0\verify_code.py", line 27, in get_image_code
    name, text, image_data = captcha.generate_captcha()
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\utils\captcha\captcha.py", line 220, in generate_captcha
    return self.captcha("")  # ×îÖÕ·µ»ØÖµ
  File "E:\wwwroot\flask_°®¼Ò×â·¿\ihome\utils\captcha\captcha.py", line 211, in captcha
    image.save(out, format=fmt)
  File "E:\env\my_flask\lib\site-packages\PIL\Image.py", line 2102, in save
    save_handler(self, fp, filename)
  File "E:\env\my_flask\lib\site-packages\PIL\JpegImagePlugin.py", line 766, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "E:\env\my_flask\lib\site-packages\PIL\ImageFile.py", line 511, in _save
    fp.write(d)
TypeError: string argument expected, got 'bytes'
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:25:58] "[35m[1mGET /api/v1/image_codes/123 HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:25:58] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:38:53] "[37mGET /api/v1/image_codes/123 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:38:58] "[37mGET /api/v1/image_codes/123 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:38:59] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:39:02] "[37mGET /api/v1/image_codes/123 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 18:39:02] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET / HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/css/reset.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/css/ihome/main.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/css/ihome/index.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/images/logo@128x59.png HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/images/home01.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/js/jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/js/template.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/js/ihome/index.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/images/home02.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:37:34] "[36mGET /static/images/home03.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:09] "[33mGET /api/v1.0/register.html HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:40] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:40] "[36mGET /static/css/ihome/register.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:40] "[36mGET /static/js/ihome/register.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:40] "[37mGET /api/v1.0/image_codes/d5d16949-1501-48c3-bb7e-b7a87054347f HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:41] "[37mGET /api/v1.0/image_codes/cac3f9d0-b632-489d-8464-c86a8bfd97f5 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:42] "[37mGET /api/v1.0/image_codes/65e1e34c-282f-4bd7-b0e7-974a415957f9 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:43] "[37mGET /api/v1.0/image_codes/78c7400e-71f9-4355-bd87-173c05c6d001 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Mar/2020 22:38:44] "[37mGET /api/v1.0/image_codes/4e1157f2-461b-4785-83a2-e6d2d2bcce0d HTTP/1.1[0m" 200 -
